import { useCallback, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ClipboardCheck } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { PageHeader } from '../../components/PageHeader'
import { EmptyState, Panel } from '../../components/ui'
import { completeStandaloneRun, listStandaloneRunItems, recordStandaloneResult, resolveStandaloneProbe } from '../../lib/standalone-tests'

const COLORS=['red','yellow','green','purple'] as const
export function TeacherTestRunPage(){const {runId}=useParams();const navigate=useNavigate();const [items,setItems]=useState<Array<any>>([]);const [message,setMessage]=useState('');const load=useCallback(async()=>{if(!runId)return;const r=await listStandaloneRunItems(runId);if(r.ok)setItems(r.data);else setMessage(r.error)},[runId]);useEffect(()=>{void load()},[load]);const current=useMemo(()=>items.find(i=>!i.standalone_test_attempts?.length||!['finalized','corrected'].includes(i.standalone_test_attempts[0]?.standalone_test_attempt_snapshots?.status)),[items]);async function color(value:typeof COLORS[number]){if(!current)return;const r=await recordStandaloneResult(current.id,value);if(!r.ok)return setMessage(r.error);setMessage(r.data.status==='probe_open'?`Green requires probe resolution · attempt ${r.data.attemptId}`:`Recorded ${value}`);await load()}async function probe(outcome:'fail'|'continue'|'done'){const attempt=current?.standalone_test_attempts?.[0];if(!attempt)return;const r=await resolveStandaloneProbe(attempt.id,outcome);if(!r.ok)return setMessage(r.error);setMessage(`Probe ${outcome} · ${r.data.status}`);await load()}async function finish(){if(!runId)return;const r=await completeStandaloneRun(runId);if(!r.ok)return setMessage(r.error);navigate('/teacher/tests')}
return <><PageHeader icon={ClipboardCheck} kicker="One-to-one Test" title={current?`Item ${current.item_order}`:'Session complete'} subtitle={`${items.filter(i=>i.standalone_test_attempts?.[0]?.standalone_test_attempt_snapshots?.status==='finalized'||i.standalone_test_attempts?.[0]?.standalone_test_attempt_snapshots?.status==='corrected').length}/${items.length||10} finalized`}/>{items.length===0?<EmptyState icon={ClipboardCheck} title="Loading frozen Test Items…" description={message}/>:<Panel icon={CheckCircle2} title={current?current.prompt_text:'All items finalized'} description="Result lifecycle is stored separately from Live Session.">{current?<><div className="observe-prompt-text">{current.prompt_text}</div><div className="btn-row">{COLORS.map(c=><button key={c} className={`capture-dot ${c}`} onClick={()=>void color(c)}>{c}</button>)}</div>{current.standalone_test_attempts?.[0]?.standalone_test_attempt_snapshots?.status?.includes('probe')?<div className="btn-row"><button onClick={()=>void probe('fail')}>Fail</button><button onClick={()=>void probe('continue')}>Continue</button><button onClick={()=>void probe('done')}>Done</button></div>:null}</>:<button className="primary" onClick={()=>void finish()}>Complete Test Session</button>}{message?<p className="meta">{message}</p>:null}</Panel>}</>}
