-- Publish a corrected immutable RED-TEST version whose 49 item texts match the approved TTS audio.
begin;
create temporary table red_test_tts_text_sync (session_number integer not null,item_number integer not null,text_vi text not null,text_en text not null,primary key (session_number,item_number)) on commit drop;
insert into red_test_tts_text_sync values
(1,1,'buổi sáng / ngon lành','morning / delicious'),(1,2,'xe đạp / đi','bicycle / ride'),(1,3,'quyển sách / đọc','book / read'),(1,4,'âm nhạc / thư giãn','music / relax'),(1,5,'gia đình / ấm áp','family / warm'),(1,6,'công viên / chạy','park / run'),(1,7,'bãi biển / đẹp','beach / beautiful'),
(2,1,'Duyệt / do đó / đề xuất','Approve / therefore / proposal'),(2,2,', có thể nói vậy / ví dụ / rõ ràng',', so to speak / for example / clear'),(2,3,'Cải thiện / bởi thế / chất lượng','Work on / for that reason / quality'),(2,4,'Quản trị / sau đó / hiệu quả','Management / then / efficiently'),(2,5,'Nguyên tắc / ngoài ra / tuân thủ','Philosophy / besides / follow'),(2,6,'Dài dòng / cuối cùng / trọng tâm','Lengthy / finally / main point'),(2,7,'Dầu gió / nếu không / dễ chịu','Medicated oil / otherwise / soothing'),
(3,1,'Cái máy lạnh / vì vậy / êm ru / ổn định','AC / so / quietly / stable'),(3,2,'Cứ thoải mái / mặc dù / cởi mở / ý kiến','Freely / although / openly / opinion'),(3,3,'Kỹ sư trưởng / đồng thời / đầu tàu / quyết đoán','Chief engineer / meanwhile / team leader / decisive'),(3,4,'Kỹ năng và khả năng / nói cách khác / mài giũa / mỗi ngày','Skill and ability / in other words / sharpen / daily'),(3,5,'Thực tập sinh / sau cùng / non tay / học hỏi','Intern / eventually / inexperienced / learn'),(3,6,'Có lẽ / trước đó / le lói / khả năng','Perhaps / before that / slight hope / possibility'),(3,7,'Duyệt / hơn nữa / bật đèn / kế hoạch','Approve / in addition / greenlight / plan'),
(4,1,'Dễ (kiếm tiền) / thu hút','Easy money / attract'),(4,2,'Hợp đồng / ký','Contract / sign'),(4,3,'Ký một cái hợp đồng / cẩn thận','Sign a contract / carefully'),(4,4,'Trước tiên / bước đầu','First / first step'),(4,5,'Thương lượng / mức giá','Negotiate / price'),(4,6,'Ồn ào / tiếng ồn','Noisy / noise'),(4,7,'Đồng nghiệp / hữu ích','Coworker / helpful'),
(5,1,'Nhiều khi / tuy nhiên / cuộc họp','Sometimes / however / meeting'),(5,2,'Tôi e là không / do đó / không thể','I''m afraid not / therefore / impossible'),(5,3,'(Ý anh) là sao? / ví dụ / bối cảnh','What''d you mean? / for example / context'),(5,4,'Phức tạp / bởi thế / quy trình','Complicated / for that reason / process'),(5,5,'Mỗi 5 năm / sau đó / chính sách','Every 5 years / then / policy'),(5,6,'Thông thường / ngoài ra / thói quen','Usually / besides / habit'),(5,7,'Vấn đề thiếu hụt nhân lực / cuối cùng / nghiêm trọng','Staff shortage / finally / serious'),
(6,1,'Tốt hơn là cậu nên / nếu không / nước đi hay / chuyên gia','You''d better / otherwise / wise move / specialist'),(6,2,'Chuỗi cung ứng / vì vậy / mắt xích yếu / mong manh','Supply chain / so / weak link / fragile'),(6,3,'Thiếu hụt / mặc dù / sắp cạn / nghiêm trọng','Shortage / although / running low / severe'),(6,4,'Đại dịch / đồng thời / cháy lan / đột ngột','Pandemic / meanwhile / wildfire / sudden'),(6,5,'Chính phủ Trung Quốc / nói cách khác / thế lực lớn / can thiệp','Chinese government / in other words / power player / intervene'),(6,6,'đóng cửa / sau cùng / tắt ngấm / nhà máy','Shut down / eventually / go dark / factory'),(6,7,'Nỗi đau thật sự / trước đó / vấn đề gai / tốn kém','Real pain point / before that / thorny issue / costly'),
(7,1,'Ở đâu / ngược lại / âm ỉ / Trào ngược dạ dày','Where / in contrast / lingering / Acid reflux'),(7,2,'Như thế nào / tiếp theo / bỏng rát / Ợ nóng','How / next / burning / Heartburn'),(7,3,'Bao lâu / dù vậy / tăng vọt / Đường huyết','How long / nevertheless / spike / Blood sugar'),(7,4,'Cái gì / nếu / Ăn chín uống sôi / Ngộ độc thực phẩm','What / if / Cook food and boil water / Food poisoning'),(7,5,'Khi nào / trong khi / cứng đầu / Ngấn mỡ bụng','When / while / stubborn / Love handles'),(7,6,'Bao nhiêu / ngược lại / hết lòng / Có tâm','How much / in contrast / wholehearted / Dedicated'),(7,7,'Tại sao / miễn là / xa vời / Còn khuya mới','Why / as long as / distant / Nowhere near');
create temporary table red_test_version_context(old_version_id uuid primary key,new_version_id uuid not null unique,package_id uuid not null) on commit drop;
insert into red_test_version_context select v.id,gen_random_uuid(),v.package_id from public.test_package_versions v where v.id='616288f1-62d1-412c-9356-f8fc92057b01'::uuid and v.status='published';
create temporary table red_test_section_map(old_id uuid primary key,new_id uuid not null unique,section_order integer not null unique) on commit drop;
insert into red_test_section_map select s.id,gen_random_uuid(),s.section_order from public.test_sections s where s.package_version_id='616288f1-62d1-412c-9356-f8fc92057b01'::uuid;
create temporary table red_test_item_map(old_id uuid primary key,new_id uuid not null unique,session_number integer not null,item_number integer not null,unique(session_number,item_number)) on commit drop;
insert into red_test_item_map select i.id,gen_random_uuid(),s.section_order,i.item_order from public.test_items i join public.test_sections s on s.id=i.section_id where i.package_version_id='616288f1-62d1-412c-9356-f8fc92057b01'::uuid;
do $$ declare c_context int;c_sections int;c_items int;c_text int;c_snapshots int;c_variants int; begin select count(*) into c_context from red_test_version_context;select count(*) into c_sections from red_test_section_map;select count(*) into c_items from red_test_item_map;select count(*) into c_text from red_test_tts_text_sync;select count(*) into c_snapshots from public.section_measurement_snapshots where package_version_id='616288f1-62d1-412c-9356-f8fc92057b01';select count(*) into c_variants from public.narration_variants where package_version_id='616288f1-62d1-412c-9356-f8fc92057b01';if c_context<>1 or c_sections<>7 or c_items<>49 or c_text<>49 or c_snapshots<>7 or c_variants<>65 then raise exception 'RED-TEST clone scope mismatch';end if;if exists(select 1 from public.test_package_versions v join red_test_version_context c on c.package_id=v.package_id where v.version_label='LIVE-TTS-SYNC-20260801') then raise exception 'Corrected RED-TEST version label already exists';end if;end $$;
insert into public.test_package_versions(id,package_id,version_label,status,draft_of_version_id,snapshot_hash,source_metadata,created_by_user_id,published_by_user_id,published_at,archived_at)
select c.new_version_id,v.package_id,'LIVE-TTS-SYNC-20260801','draft',v.id,null,v.source_metadata||jsonb_build_object('textSyncSource','option-1-audio-source.txt','audioSet','option-1-tts-49','clonedFromVersionId',v.id,'textSyncedAt','2026-08-01T15:41:00Z'),v.created_by_user_id,v.published_by_user_id,null,null from public.test_package_versions v join red_test_version_context c on c.old_version_id=v.id;
insert into public.test_sections(id,package_version_id,section_order,title,target_cvr_ohm,cci_profile_id,cci_category_id,cci_snapshot,intro_text_vi,intro_text_en,metadata)
select m.new_id,c.new_version_id,s.section_order,s.title,s.target_cvr_ohm,s.cci_profile_id,s.cci_category_id,s.cci_snapshot,s.intro_text_vi,s.intro_text_en,s.metadata||jsonb_build_object('clonedFromSectionId',s.id) from public.test_sections s join red_test_section_map m on m.old_id=s.id cross join red_test_version_context c;
insert into public.test_items(id,package_version_id,section_id,item_order,source_day,source_stt,term_vi,term_en,prompt_vi,prompt_en,tc,lc,tl,cvr_breakdown,source_metadata,spoken_script_vi,spoken_script_en)
select im.new_id,c.new_version_id,sm.new_id,i.item_order,i.source_day,i.source_stt,x.text_vi,x.text_en,x.text_vi,x.text_en,i.tc,i.lc,i.tl,i.cvr_breakdown,i.source_metadata||jsonb_build_object('clonedFromItemId',i.id,'ttsTextSync',jsonb_build_object('syncedAt','2026-08-01T15:41:00Z','source','option-1-audio-source.txt','audioSet','option-1-tts-49','previous',jsonb_build_object('term_vi',i.term_vi,'term_en',i.term_en,'prompt_vi',i.prompt_vi,'prompt_en',i.prompt_en,'spoken_script_vi',i.spoken_script_vi,'spoken_script_en',i.spoken_script_en))),x.text_vi,x.text_en from public.test_items i join red_test_item_map im on im.old_id=i.id join red_test_section_map sm on sm.old_id=i.section_id join red_test_tts_text_sync x on x.session_number=im.session_number and x.item_number=im.item_number cross join red_test_version_context c;
insert into public.section_measurement_snapshots(id,test_section_id,package_version_id,target_cvr_ohm,cci_profile_id,cci_category_id,cci_category_label,cci_value,snapshot_metadata,supersedes_snapshot_id,override_reason,created_by_user_id)
select gen_random_uuid(),sm.new_id,c.new_version_id,snap.target_cvr_ohm,snap.cci_profile_id,snap.cci_category_id,snap.cci_category_label,snap.cci_value,snap.snapshot_metadata||jsonb_build_object('clonedFromSnapshotId',snap.id),null,null,snap.created_by_user_id from public.section_measurement_snapshots snap join red_test_section_map sm on sm.old_id=snap.test_section_id cross join red_test_version_context c where snap.package_version_id=c.old_version_id;
insert into public.narration_variants(id,package_version_id,test_section_id,test_item_id,narration_target,language,voice_id,voice_label,source_text_hash,provider_metadata,audio_asset_id,approval_status,approved_by_user_id,approved_at,generation_job_id)
select gen_random_uuid(),c.new_version_id,case when nv.test_section_id is null then null else sm.new_id end,case when nv.test_item_id is null then null else im.new_id end,nv.narration_target,nv.language,nv.voice_id,nv.voice_label,case when nv.narration_target='test_item' then 'sha256:'||encode(digest((case nv.language when 'vi' then x.text_vi else x.text_en end)||':'||nv.language||':'||nv.voice_id,'sha256'),'hex') else nv.source_text_hash end,nv.provider_metadata||jsonb_build_object('clonedFromVariantId',nv.id,'clonedFromVersionId',c.old_version_id,'textSyncedAt','2026-08-01T15:41:00Z','textSource','option-1-audio-source.txt'),nv.audio_asset_id,nv.approval_status,nv.approved_by_user_id,nv.approved_at,null from public.narration_variants nv cross join red_test_version_context c left join red_test_section_map sm on sm.old_id=nv.test_section_id left join red_test_item_map im on im.old_id=nv.test_item_id left join red_test_tts_text_sync x on x.session_number=im.session_number and x.item_number=im.item_number where nv.package_version_id=c.old_version_id;
do $$ declare v_new uuid;c_sections int;c_items int;c_snapshots int;c_variants int;c_approved_items int;c_mismatch int;begin select new_version_id into v_new from red_test_version_context;select count(*) into c_sections from public.test_sections where package_version_id=v_new;select count(*) into c_items from public.test_items where package_version_id=v_new;select count(*) into c_snapshots from public.section_measurement_snapshots where package_version_id=v_new;select count(*) into c_variants from public.narration_variants where package_version_id=v_new;select count(*) into c_approved_items from public.narration_variants where package_version_id=v_new and narration_target='test_item' and approval_status='approved' and audio_asset_id is not null;select count(*) into c_mismatch from public.test_items i join public.test_sections s on s.id=i.section_id join red_test_tts_text_sync x on x.session_number=s.section_order and x.item_number=i.item_order where i.package_version_id=v_new and (i.term_vi is distinct from x.text_vi or i.term_en is distinct from x.text_en or i.prompt_vi is distinct from x.text_vi or i.prompt_en is distinct from x.text_en or i.spoken_script_vi is distinct from x.text_vi or i.spoken_script_en is distinct from x.text_en);if c_sections<>7 or c_items<>49 or c_snapshots<>7 or c_variants<>65 or c_approved_items<>49 or c_mismatch<>0 then raise exception 'Corrected clone validation failed';end if;end $$;
with snapshot_payload as (select c.new_version_id,jsonb_build_object('packageVersionId',c.new_version_id,'voiceVi','gemini/gemini-2.5-flash-preview-tts/Kore','voiceEn','gemini/gemini-2.5-flash-preview-tts/Kore','sections',jsonb_agg(jsonb_build_object('id',s.id,'order',s.section_order,'title',s.title,'introVi',s.intro_text_vi,'introEn',s.intro_text_en,'items',(select jsonb_agg(jsonb_build_object('id',i.id,'order',i.item_order,'promptVi',i.prompt_vi,'promptEn',i.prompt_en,'spokenVi',i.spoken_script_vi,'spokenEn',i.spoken_script_en,'tc',i.tc,'lc',i.lc,'tl',i.tl) order by i.item_order) from public.test_items i where i.section_id=s.id)) order by s.section_order)) payload from red_test_version_context c join public.test_sections s on s.package_version_id=c.new_version_id group by c.new_version_id),hashes as (select new_version_id,'sha256:'||encode(digest(convert_to(payload::text,'UTF8'),'sha256'),'hex') snapshot_hash from snapshot_payload)
update public.test_package_versions v set snapshot_hash=h.snapshot_hash,source_metadata=v.source_metadata||jsonb_build_object('publishedVoiceVi','gemini/gemini-2.5-flash-preview-tts/Kore','publishedVoiceEn','gemini/gemini-2.5-flash-preview-tts/Kore') from hashes h where v.id=h.new_version_id and v.status='draft';
update public.test_package_versions v set status='published',published_at=now() from red_test_version_context c where v.id=c.new_version_id and v.status='draft' and v.snapshot_hash is not null;
update public.test_package_versions v set status='archived' from red_test_version_context c where v.id=c.old_version_id and v.status='published' and exists(select 1 from public.test_package_versions n where n.id=c.new_version_id and n.status='published');
commit;;
